# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@v3
   
    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.21.5'

    - name: Build
      run: go build -o bin/echoserver

    - name: commit and push
      run: |
        git config --global user.name "saravanancitian"
        git config --global user.email "saravanancitian@live.in"
        git add bin/echoserver
        git commit -m "Add compiled executable"
        git push 